import { createRequire } from 'module';
const require = createRequire(import.meta.url);
global.window = { React: require('react') };
require('<SANDBOX>/ds/build/bundle.js');
global.btoa = s => Buffer.from(s, 'binary').toString('base64'); global.atob = s => Buffer.from(s, 'base64').toString('binary');
const A = await import('./src/aprobacion.js');
const M = await import('./src/model.js');
const { proceso } = await import('./seed.mjs');
let f = 0; const ok = (c, m) => { if (!c) f++; console.log((c ? 'OK   ' : 'FALLA') + ' ' + m); };
const p = M.normalizarProceso(JSON.parse(JSON.stringify(proceso)));
ok(A.prefijoProceso(p.nombre) === 'CBM', 'prefijo: ' + A.prefijoProceso(p.nombre));
ok(A.prefijoProceso('Radicación de facturas') === 'RF' && A.prefijoProceso('Nómina') === 'NOM', 'prefijos: RF, NOM');
const cods = p.participantes.map(c => A.codigoContacto(p, c));
console.log('códigos:', cods.join(' '));
ok(cods.every(c => /^CBM-0\d-[A-Z2-9]{4}$/.test(c)) && new Set(cods).size === cods.length, 'formato y únicos');
ok(A.codigoContacto(p, p.participantes[0]) === cods[0], 'estables');
const m = p.versiones.asis;
m.aprobacion = A.nuevaSolicitud(p, m, { conVobo: true, vobo: ['u_marta', 'u_carlos'], final: ['u_rosa', 'u_laura'], remitente: { nombre: 'Paul', correo: 'paul@ejemplo.co' } });
m.estado = 'revision';
ok(m.aprobacion.etapas.length === 2 && A.etapaEnCurso(m.aprobacion) === 0, 'dos etapas, en curso la 1');
// Respuesta armada como en la fotografía
const resp = (per, etapa, d, msg, pp, mm) => {
  pp = pp || p; mm = mm || m;
  const dat = { a: 'kzr1', p: pp.id, pn: pp.nombre, v: 'asis', n: mm.numero, r: mm.aprobacion.id, e: etapa, c: per.codigo, d, m: msg || '', f: new Date().toISOString(), q: per.nombre };
  const cod = A.codificarRespuesta(dat);
  return 'Hola Paul:\n\nDoy mi visto bueno.\n\n--- Código de respuesta (no lo modifiques) ---\n' + cod.replace(/(.{60})/g, '$1\n') + '\n--- Fin del código ---\n\n' + per.nombre;
};
const marta = m.aprobacion.etapas[0].personas[0];
let r = A.interpretarRespuesta(p, m, 'asis', resp(marta, 'vobo', 'aprobado'));
ok(!r.error && r.persona.id === 'u_marta' && r.decision === 'aprobado', 'lee la respuesta aunque el correo parta el código en líneas: ' + (r.error || r.persona.nombre));
const rosa = m.aprobacion.etapas[1].personas[0];
r = A.interpretarRespuesta(p, m, 'asis', resp(rosa, 'final', 'aprobado'));
ok(r.error && /aún no está abierta/.test(r.error), 'la etapa final espera: ' + r.error);
r = A.interpretarRespuesta(p, m, 'asis', resp(marta, 'vobo', 'aprobado').replace(/KZR1\.(.)/, 'KZR1.X'));
ok(r.error && /incompleto|cambio/.test(r.error), 'detecta un código alterado: ' + r.error);
A.registrarRespuesta(p, m, { etapa: 0, persona: 'u_marta', decision: 'aprobado', via: 'codigo' });
r = A.interpretarRespuesta(p, m, 'asis', resp(marta, 'vobo', 'aprobado'));
ok(r.error && /ya respondió/.test(r.error), 'no registra dos veces: ' + r.error);
A.registrarRespuesta(p, m, { etapa: 0, persona: 'u_carlos', decision: 'aprobado', via: 'codigo' });
ok(A.etapaEnCurso(m.aprobacion) === 1 && m.estado === 'revision', 'con los dos VoBo se abre la aprobación final');
A.registrarRespuesta(p, m, { etapa: 1, persona: 'u_rosa', decision: 'aprobado', via: 'codigo' });
A.registrarRespuesta(p, m, { etapa: 1, persona: 'u_laura', decision: 'aprobado', via: 'codigo' });
ok(m.estado === 'aprobado' && m.historial.length === 1, 'aprobada: ' + JSON.stringify(m.historial[0]));
// cambios
const p2 = M.normalizarProceso(JSON.parse(JSON.stringify(proceso))); const m2 = p2.versiones.asis;
m2.aprobacion = A.nuevaSolicitud(p2, m2, { conVobo: false, vobo: [], final: ['u_rosa'], remitente: { nombre: 'Paul', correo: 'p@e.co' } }); m2.estado = 'revision';
const rosa2 = m2.aprobacion.etapas[0].personas[0];
r = A.interpretarRespuesta(p2, m2, 'asis', resp(rosa2, 'final', 'cambios', 'La revisión la hace tesorería', p2, m2));
ok(!r.error && r.decision === 'cambios' && r.comentario === 'La revisión la hace tesorería', 'lee un pedido de cambios con acentos: ' + (r.error || r.comentario));
A.registrarRespuesta(p2, m2, Object.assign({ etapa: r.etapa, persona: r.persona.id, decision: r.decision, comentario: r.comentario, via: 'codigo' }));
ok(m2.estado === 'cambios' && p2.preguntas.some(q => /tesorería/.test(q.texto)), 'el flujo vuelve: cambios + pregunta');
r = A.interpretarRespuesta(p, m2, 'asis', resp(rosa2, 'final', 'aprobado'));
ok(r.error && /otro proceso|no está en revisión|envío anterior/.test(r.error), 'otro proceso o ronda: ' + r.error);
// legado
const p3 = JSON.parse(JSON.stringify(proceso)); p3.versiones.asis.aprobacion = { version: 1, solicitada: '2026-09-20T10:00:00Z', aprobadores: [{ rol: 'dueno', nombre: 'Rosa Álvarez', titulo: 'Dueño del proceso' }], respuestas: { dueno: { decision: 'aprobado', fecha: '2026-09-21T10:00:00Z' } } };
M.normalizarProceso(p3);
ok(p3.versiones.asis.aprobacion.etapas && M.estadoAprobacion(p3.versiones.asis.aprobacion) === 'aprobado', 'aprobación antigua convertida');
const inv = A.correoInvitacion(p, m, 'asis', m.aprobacion, m.aprobacion.etapas[0], marta);
console.log('--- invitación ---\n' + A.textoCorreo(inv));
const l = A.enlacesCorreo(inv);
ok(l.mailto.startsWith('mailto:marta.rios@ejemplo.co?subject=') && l.gmail.includes('to=marta.rios%40ejemplo.co'), 'enlaces de correo');
console.log(f ? f + ' FALLAS' : 'TODO OK');
