const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const DS = '<SANDBOX>/ds/out/project/components/lib/';
const FAKE = `window.claude = { use: async n => n === 'downloads' ? { save: async r => { window.__d = (window.__d || []).concat([r.filename]); return { status: 'saved' }; } } : null };`;
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const ctx = await b.newContext({ viewport: { width: 1280, height: 860 } });
  await ctx.route('https://cdnjs.cloudflare.com/**', r => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync(DS + (r.request().url().includes('react-dom') ? 'react-dom.production.min.js' : 'react.production.min.js'), 'utf8') }));
  await ctx.route('https://cdn.jsdelivr.net/**', r => { const u = r.request().url(); const f = u.includes('docx') ? require('child_process').execSync('npm root -g').toString().trim() + '/docx/dist/index.iife.js' : path.join(__dirname, 'package/dist/bpmn-modeler.production.min.js'); r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync(f, 'utf8') }); });
  await ctx.route(u => u.hostname.startsWith('fonts.'), r => r.fulfill({ contentType: 'text/css', body: '' }));
  await ctx.addInitScript(FAKE);
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
  const url = 'file://' + path.join(__dirname, 'out/test.html');
  await p.goto(url); await p.waitForSelector('.tabla-procesos tbody tr');
  console.log('1 lista:', await p.$$eval('.proc-nom', e => e.map(x => x.textContent)), '| nota:', await p.$eval('.contenido > .nota', e => e.textContent));
  await p.screenshot({ path: 'out/l1-lista.png' });
  await p.click('.enlace-fila'); await p.waitForSelector('.tabs');
  console.log('2 botones IA visibles:', await p.$$eval('button', bs => bs.filter(x => /IA/.test(x.textContent)).length));
  await p.click('button[role=tab]:has-text("Actividades")');
  await p.fill('[data-fase="__sin"] .kz-alta', 'Verificar firmas'); await p.press('[data-fase="__sin"] .kz-alta', 'Enter');
  await p.waitForTimeout(900);
  await p.reload(); await p.waitForSelector('.tabla-procesos tbody tr');
  await p.click('.enlace-fila'); await p.click('button[role=tab]:has-text("Actividades")');
  console.log('3 persiste tras recargar:', await p.$$eval('.kz-card__name', e => e.some(x => x.textContent === 'Verificar firmas')));
  await p.click('button[role=tab]:has-text("Diagrama")'); await p.waitForSelector('.djs-element', { timeout: 8000 });
  await p.click('button:has-text("Exportar .bpmn")'); await p.waitForTimeout(200);
  console.log('4 descargas:', await p.evaluate(() => window.__d));
  await p.click('.miga'); await p.waitForSelector('.tabla-procesos');
  await p.click('.tabla-procesos .kz-link'); await p.click('.confirmar button:has-text("Eliminar")'); await p.waitForTimeout(200);
  console.log('5 tras eliminar, aviso:', await p.$eval('.contenido .aviso', e => e.textContent));
  await p.click('button:has-text("Cargar el proceso de ejemplo")'); await p.waitForSelector('.tabla-procesos tbody tr');
  console.log('6 ejemplo restablecido:', await p.$$eval('.proc-nom', e => e.map(x => x.textContent)));
  console.log('ERRORES:', errs.length ? errs : 'ninguno');
  await b.close();
})().catch(e => { console.error('FALLO', e.message); process.exit(1); });
